services:
  - type: web
    name: thinky-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd thinky && python manage.py migrate --noinput && gunicorn thinky.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
