# Generated by Django 6.0.3 on 2026-03-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_studentskillmastery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlevel',
            name='points_rewarded',
        ),
        migrations.RemoveField(
            model_name='userlevel',
            name='score',
        ),
        migrations.AddField(
            model_name='userlevel',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
