# Generated by Django 6.0.3 on 2026-03-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0004_remove_userlevel_points_rewarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='intro_message',
            field=models.TextField(default=''),
        ),
    ]
