# Generated by Django 5.2.12 on 2026-04-20 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0008_planetcard_level_planet_name_userunlockedcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='is_homework',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='level',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_levels', to=settings.AUTH_USER_MODEL),
        ),
    ]
