# Generated by Django 6.0.3 on 2026-07-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0010_gameworld_level_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameworld',
            name='points_to_open',
            field=models.IntegerField(default=0),
        ),
    ]
