# Generated by Django 6.0.3 on 2026-08-15 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0011_gameworld_points_to_open'),
        ('users', '0007_user_parent_of_user_role_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_levels', to='users.classroom'),
        ),
    ]
