# Generated by Django 6.0.3 on 2026-03-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0002_gamesession_finished_gamesession_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='energy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='phase',
            field=models.CharField(choices=[('analysis', 'Analysis'), ('training', 'Training'), ('testing', 'Testing')], default='analysis', max_length=20),
        ),
    ]
