# Generated by Django 6.0.3 on 2026-03-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_hint_alter_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
