# Generated by Django 5.2.12 on 2026-05-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='error_type_a',
            field=models.CharField(choices=[('none', 'None (Correct or Unspecified)'), ('calculation', 'Calculation Error'), ('multiplication_table', 'Multiplication Table Error'), ('sign_error', 'Sign Error'), ('misunderstanding', 'Misunderstanding the Question'), ('forgetting_steps', 'Forgetting Steps')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='error_type_b',
            field=models.CharField(choices=[('none', 'None (Correct or Unspecified)'), ('calculation', 'Calculation Error'), ('multiplication_table', 'Multiplication Table Error'), ('sign_error', 'Sign Error'), ('misunderstanding', 'Misunderstanding the Question'), ('forgetting_steps', 'Forgetting Steps')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='error_type_c',
            field=models.CharField(choices=[('none', 'None (Correct or Unspecified)'), ('calculation', 'Calculation Error'), ('multiplication_table', 'Multiplication Table Error'), ('sign_error', 'Sign Error'), ('misunderstanding', 'Misunderstanding the Question'), ('forgetting_steps', 'Forgetting Steps')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='error_type_d',
            field=models.CharField(choices=[('none', 'None (Correct or Unspecified)'), ('calculation', 'Calculation Error'), ('multiplication_table', 'Multiplication Table Error'), ('sign_error', 'Sign Error'), ('misunderstanding', 'Misunderstanding the Question'), ('forgetting_steps', 'Forgetting Steps')], default='none', max_length=50),
        ),
    ]
