# Generated by Django 5.2.12 on 2026-04-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_store', '0002_alter_userstore_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
