# Generated by Django 6.0.3 on 2026-03-13 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
        ('questions', '0002_alter_question_hint_alter_question_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='questions.question'),
        ),
    ]
