# Generated by Django 5.2.12 on 2026-03-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_alter_points_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
