# Generated by Django 6.0.3 on 2026-03-15 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerattempt',
            name='attempt_number',
        ),
    ]
