# Generated by Django 5.2.12 on 2026-03-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_remove_answerattempt_attempt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerattempt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
