# Generated by Django 5.2.12 on 2026-04-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_alter_answerattempt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerattempt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
