# Generated by Django 6.0.3 on 2026-03-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='required_score',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='points_rewarded',
            field=models.IntegerField(default=0),
        ),
    ]
