# Generated by Django 5.2.12 on 2026-03-28 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0003_gamesession_energy_gamesession_is_active_and_more'),
        ('questions', '0004_question_allowed_time_alter_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='active_character',
            field=models.CharField(default='hakeem', max_length=50),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='ai_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='current_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='next_difficulty',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='target_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.skill'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
